### PR TITLE
add contributor information

### PR DESCRIPTION
**Pull request by flynnduism**
Adds a contributor section to the [website](https://krustlet.dev/) to signify the collaboration between Microsoft and CapitalOne on this project. 
[Preview the logo usage here](https://deploy-preview-2--krustlet-dev.netlify.app/).

--

Signed-off-by: flynnduism <dev@ronan.design>

### CODE REVIEW

**Comment by flynnduism** [comment]
@LiamRandall 👋 

How does this look, can we use your logo in our Krustlet contribution section?

**Review by thomastaylor312 — APPROVED** [review]
This is good on my end so long as we get permission from CapitalOne to use it

**Comment by LiamRandall** [comment]
Sending this over to our PR team now.

**Comment by flynnduism** [comment]
Closing this as PR to update info on the contributors, it's gotten stale.

Contributors can use this as a reference to add logos as needed.

**Pull request closed without merging**
